version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=DORIME'
      - 'POSTGRES_DB=library_db'
    ports:
    - '5432:5431'
  app:
    build: ./
    container_name: 'java-app'
    ports:
    - 8081:8081