spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/library_db
    password: DORIME
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    port: 587
    username: electroniclibrarysystem@gmail.com
    password: "jponxzgzxkexbpbh"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: '8081'
